baseurl: ''
exclude: ['README.md']
permalink: pretty
title: 'Karishma Financial Services'

collections:
  services:
    output: true
    permalink: /services/:path/
  team:
    output: true
    permalink: /team/:path/
  testimonials:
    output: true
    permalink: /testimonials/:path/
  debt: 
    output: true
    permalink: /debt/:path/
  models:
    output: true
    permalink: /model/:path/

defaults:
  - scope:
      type: services
    values:
      layout: service
      bodyClass: page-services-single
  - scope:
      type: debt
    values:
      layout: debt
      bodyClass: page-debt-single
  - scope:
      path: 'images'
    values:
      image: true

sass:
  style: compact # possible values: nested expanded compact compressed

google_analytics_id: null

plugins:
  - jekyll-environment-variables
